[package]
name = "kinematics-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "=1.0.24"
ndarray = "0.15.6"
rust_decimal = {version ="1.35.0", features = ["maths"]}
rust_decimal_macros = "1.35.0"
libm = "0.2.8"